### ISSUE TITLE
E-mailing Photo

### ISSUE THREAD

**Issue by jrivas1218** [wyolum/TouchSelfie#13]
Hi, I've been working on this project for school and have gotten everything to work fine except the only problem that I keep stumbling upon is when I try to e-mail myself the picture that I take. In terminal it reads "sending photo by email to 'email address' " at first. However, during this time it freezes the application and it takes a while for it to load but when it does, terminal reads "Send Failed: [Error 101] Network is unreachable" I was wondering if you could help me solve this issue. I don't know if it's simply my network that won't let it work since it's a school network or if it's an issue deriving from when I was setting everything up in the beginning.

**Comment by wyojustin** [comment]
Make sure you have a network connection by pining google.com.

$ ping google.com

**Comment by laurentalacoque** [comment]
Hi @jrivas1218,
I had a similar issue.
I found out that my network was blocking the sendmail port (to prevent abuse). Your school might well be doing the same.
A quick and dirty solution would be to hide both the text entry and "send email" button (by commenting the lines where they're `pack`ed.

I myself resolved the problem differently: I adapted the code so that mails are sent using OAuth2 authentication. This way, email sending are not blocked anymore. (See my fork of TouchSelfie)
